### ISSUE TITLE
Codes are not 2 digits in rec24

### ISSUE THREAD

**Issue by ecki** [edi3/edi3-codelists#18]
https://github.com/edi3/edi3-codelists/blob/506c980b79f0fce9311102b6ca6f45cdb32df98d/docs/recommendation-24/datapackage.json#L23

The CSV data file in rec24 contains numerical codes with up to 3 digits. The datapackage descriptions claims otherwise, so the regular expression does not match.

**Comment by cmsdroff** [comment]
Thanks @ecki fixed :)
