### ISSUE TITLE
Recommendation 21 - numericCode

### ISSUE THREAD

**Issue by cmsdroff** [edi3/edi3-codelists#8]
For recommendation 21 there is a field in the UNECE dataset for `numericCode` this I think raises some discussion, for all my uses I've only ever used the `code` never `numericCode` but it's in there for a reason (not currently in our data.csv file).  

Looking at the data from the UNECE recommendation if we were to include it so its useful it will possibly require some re-work.

For example:
<img width="833" alt="Screenshot 2019-05-17 at 10 09 02" src="https://user-images.githubusercontent.com/2013960/57909999-d96c0380-788c-11e9-9d42-1d0c2dfea2af.png">

There are many `numericCode` represented under a single code how useful is this the way its provided today, should we create a separate line repeating the `code` for each `numericCode` or flip it the other way and create a dataset to return for the `numericCode`

Thoughts on relevance, how to approach most welcome

**Comment by kshychko** [comment]
I missed that numericCode is not in the current data.csv
I would add it as an array property to the PackageType definition and keep it as allowed query parameter, so it will return a list of corresponding package types. I don't think we should repeat codes per each corresponding numericCode, as it seems enough for me to be able to query a subset of package types by specifying the numeric code.

**Comment by rgenoulaz** [comment]
ok why not then, let's put an array property for this, I'm not quite confident that there will actually be such usage but let's stay open-minded :)

**Comment by cmsdroff** [comment]
@rgenoulaz agree I’m unsure on the practical application, but conscious of there must have been a use case for it to be added, I actually read up on the pdf the below.  So it looks like the numeric was originally the preference, and maybe the alpha numeric simply became more adopted by trade.

> **VIII. CHOICE BETWEEN NUMERIC AND ALPHABETIC CODES**
> **31.** Users can choose between structured numeric and alphabetic codes. Numeric codes may be preferable for ADP as they are structured whereas alphabetic codes offer more permutation possibilities. In trade documents pack- age types are described mainly for the purpose of enabling the identification of the goods when these are moved and handled during transport operations and for the purpose of frontier control; in this context short alphabetic codes are often preferred, as they are easier to memorize, particularly if they provide a mnemonic link with the name of the package type.

So i think for the future and agree with @kshychko we should include and that the array property would be useful here, for the ‘maintainers’ of the code list in the UN we would ask them to separate using a comma rather than ‘or’ 

I.e. 
`23 or 24 or 25`

To replace with 

`23, 24, 25`

I can update the data.csv with this if we all agree as a way forward for this issue?

**Comment by cmsdroff** [comment]
added a pull request, if someone could check the array for the numericCode I be grateful :)

**Comment by rgenoulaz** [comment]
Hi @cmsdroff, it looks good to me, let me check the PR.
